SET NAMES utf8mb4;

-- Clear existing articles
DELETE FROM articles;

-- Reset auto-increment
ALTER TABLE articles AUTO_INCREMENT = 1;

-- ============================================================
-- CATEGORY 1: Spillover (Interface Spillover) — 5 articles
-- ============================================================

INSERT INTO articles (category_id, author_id, slug, title_fr, title_en, excerpt_fr, excerpt_en, body_fr, body_en, cover_image, status, is_featured, published_at, views) VALUES
(1, 1,
 'zoonotic-spillover-events-west-africa-2026',
 'Les événements de spillover zoonotique en Afrique de l''Ouest : une menace croissante pour la santé publique',
 'Zoonotic Spillover Events in West Africa: A Growing Threat to Public Health',
 'Une étude récente révèle une augmentation de 40 % des événements de spillover zoonotique dans la région ouest-africaine. Les chercheurs appellent à une surveillance renforcée aux interfaces faune sauvage-bétail.',
 'A new multi-country study documents a 40% increase in zoonotic spillover events across the West African corridor. Researchers are calling for urgent investment in wildlife-livestock interface monitoring.',
 'Les événements de spillover zoonotique, c''est-à-dire le passage d''agents pathogènes de la faune sauvage aux populations humaines, constituent une préoccupation majeure en Afrique de l''Ouest. Selon une étude multinationale publiée dans le Bulletin de l''Organisation Mondiale de la Santé, ces événements ont augmenté de 40 % au cours des cinq dernières années dans la sous-région. Les chercheurs attribuent cette hausse à la déforestation accélérée, à l''expansion des zones agricoles et à la proximité croissante entre les communautés humaines et les habitats de la faune sauvage.\n\nL''étude, menée par un consortium de laboratoires affiliés au CDC Afrique et à l''Institut Pasteur de Dakar, a analysé plus de 3 000 échantillons prélevés dans huit pays de la CEDEAO entre 2022 et 2025. Les résultats montrent que les marchés de viande de brousse et les zones de pâturage partagées représentent les principaux points de contact à haut risque. Les coronavirus, les paramyxovirus et les filovirus figurent parmi les familles virales les plus fréquemment détectées.\n\nLe professeur Amadou Sall, directeur de l''Institut Pasteur de Dakar, a souligné que « la surveillance intégrée aux interfaces homme-animal-environnement est désormais une nécessité absolue, pas un luxe ». Il a plaidé pour la création d''un réseau régional de sentinelles biologiques capable de détecter précocement les signaux de spillover avant qu''ils ne se transforment en épidémies.\n\nLes auteurs recommandent un investissement annuel de 50 millions de dollars pour renforcer les capacités de diagnostic rapide, former les agents de santé communautaire et établir des corridors de biosécurité autour des zones écologiques sensibles. Le CDC Afrique a déjà intégré ces recommandations dans son plan stratégique 2026-2030.',
 'Zoonotic spillover events — the transmission of pathogens from wildlife to human populations — are emerging as a critical public health concern across West Africa. A multinational study published in the WHO Bulletin has documented a 40% increase in such events over the past five years in the sub-region. Researchers attribute this surge to accelerated deforestation, agricultural expansion, and the growing proximity between human communities and wildlife habitats.\n\nThe study, conducted by a consortium of laboratories affiliated with Africa CDC and the Institut Pasteur de Dakar, analyzed over 3,000 samples collected across eight ECOWAS countries between 2022 and 2025. Findings reveal that bushmeat markets and shared grazing zones represent the primary high-risk contact points. Coronaviruses, paramyxoviruses, and filoviruses were among the most frequently detected viral families.\n\nProfessor Amadou Sall, Director of the Institut Pasteur de Dakar, emphasized that \"integrated surveillance at the human-animal-environment interface is now an absolute necessity, not a luxury.\" He advocated for the creation of a regional network of biological sentinels capable of detecting early spillover signals before they escalate into outbreaks.\n\nThe authors recommend an annual investment of $50 million to strengthen rapid diagnostic capacity, train community health workers, and establish biosecurity corridors around sensitive ecological zones. Africa CDC has already incorporated these recommendations into its 2026-2030 strategic plan.',
 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&h=500&fit=crop',
 'published', 1, '2026-01-15 08:30:00', 1120),

(1, 1,
 'wildlife-livestock-interface-east-african-rift',
 'L''interface faune sauvage-bétail dans le Rift est-africain : cartographie des risques émergents',
 'Wildlife-Livestock Interface in the East African Rift: Mapping Emerging Risks',
 'Des travaux de terrain dans la vallée du Rift identifient de nouvelles zones de contact à haut risque entre la faune sauvage et le bétail domestique. Les données de surveillance One Health sont désormais accessibles en temps réel.',
 'Field research in the Rift Valley has identified new high-risk contact zones between wildlife and domestic livestock. Real-time One Health surveillance data is now being shared across national boundaries for the first time.',
 'La vallée du Rift est-africain, qui s''étend du Mozambique à l''Éthiopie, constitue l''un des écosystèmes les plus dynamiques du continent en matière de biodiversité. Cependant, cette richesse écologique s''accompagne de risques sanitaires considérables, notamment aux points de contact entre la faune sauvage et le bétail domestique. Une équipe de recherche coordonnée par l''ILRI (International Livestock Research Institute) a récemment publié une cartographie détaillée de ces interfaces à risque.\n\nL''étude, qui a mobilisé des équipes de terrain dans cinq pays — Kenya, Tanzanie, Éthiopie, Ouganda et Rwanda — a identifié 47 zones de contact prioritaires où les interactions entre faune sauvage et bétail sont particulièrement intenses. Les analyses sérologiques ont révélé la circulation active de la fièvre de la vallée du Rift, de la brucellose et de plusieurs souches de Mycobacterium bovis résistantes aux antibiotiques conventionnels.\n\nLe Dr Delia Grace, épidémiologiste principale à l''ILRI, a déclaré que « ces résultats confirment que les politiques de santé animale ne peuvent plus être élaborées sans prendre en compte la dimension écologique ». Elle a notamment insisté sur la nécessité d''intégrer les données de surveillance de la faune sauvage dans les systèmes d''information sanitaire nationaux.\n\nGrâce à un financement de la Fondation Bill & Melinda Gates, un tableau de bord en temps réel a été déployé, permettant aux autorités vétérinaires de six pays de partager instantanément les alertes épidémiologiques. Ce système représente une avancée majeure dans l''opérationnalisation de l''approche One Health en Afrique de l''Est.',
 'The East African Rift Valley, stretching from Mozambique to Ethiopia, is one of the continent''s most biodiverse ecosystems. However, this ecological richness comes with considerable health risks, particularly at contact points between wildlife and domestic livestock. A research team coordinated by ILRI (International Livestock Research Institute) has recently published a detailed mapping of these high-risk interfaces.\n\nThe study, which mobilized field teams across five countries — Kenya, Tanzania, Ethiopia, Uganda, and Rwanda — identified 47 priority contact zones where wildlife-livestock interactions are particularly intense. Serological analyses revealed the active circulation of Rift Valley fever, brucellosis, and several strains of Mycobacterium bovis resistant to conventional antibiotics.\n\nDr. Delia Grace, senior epidemiologist at ILRI, stated that \"these findings confirm that animal health policies can no longer be developed without considering the ecological dimension.\" She emphasized the need to integrate wildlife surveillance data into national health information systems.\n\nWith funding from the Bill & Melinda Gates Foundation, a real-time dashboard has been deployed, enabling veterinary authorities in six countries to share epidemiological alerts instantaneously. This system represents a major advance in operationalizing the One Health approach in East Africa.',
 'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=800&h=500&fit=crop',
 'published', 0, '2026-02-03 10:15:00', 834),

(1, 1,
 'emerging-pathogens-congo-basin-forests',
 'Pathogènes émergents dans les forêts du bassin du Congo : alerte précoce et réponse rapide',
 'Emerging Pathogens in Congo Basin Forests: Early Warning and Rapid Response',
 'Le réseau PREDICT-Afrique a détecté trois nouvelles familles virales dans des échantillons de chauves-souris prélevés au Cameroun et en RDC. Les protocoles de réponse rapide ont été activés dans la sous-région.',
 'The PREDICT-Africa network has detected three novel viral families in bat samples collected in Cameroon and DRC. Rapid response protocols have been activated across the sub-region as authorities assess the pandemic potential.',
 'Les forêts tropicales du bassin du Congo, deuxième plus grand massif forestier au monde après l''Amazonie, abritent une biodiversité exceptionnelle qui inclut de nombreux réservoirs viraux encore méconnus. Le réseau de surveillance PREDICT-Afrique, financé par l''USAID et coordonné par le CDC Afrique, vient de révéler la découverte de trois nouvelles familles virales dans des échantillons prélevés sur des populations de chauves-souris frugivores au Cameroun et en République démocratique du Congo.\n\nLes analyses métagénomiques, réalisées dans les laboratoires de référence de Yaoundé et de Kinshasa, ont permis d''identifier des séquences génétiques apparentées aux henipavirus et aux coronavirus, mais suffisamment divergentes pour constituer des taxons distincts. Le potentiel zoonotique de ces virus fait actuellement l''objet d''évaluations approfondies, incluant des tests d''infectivité sur cultures cellulaires humaines.\n\nLe Dr Jean-Jacques Muyembe, virologue congolais de renommée mondiale et découvreur du virus Ebola, a qualifié ces découvertes de « signal d''alarme qui exige une réponse immédiate ». Il a rappelé que la majorité des pandémies du XXIe siècle trouvent leur origine dans des événements de spillover similaires survenus dans des zones forestières tropicales.\n\nEn réponse à ces découvertes, les ministères de la santé du Cameroun, de la RDC, du Gabon et de la République du Congo ont activé leurs protocoles de réponse rapide conjoints. Des équipes d''investigation épidémiologique ont été déployées dans les communautés riveraines des zones de prélèvement pour évaluer l''exposition humaine potentielle et renforcer la surveillance syndromique.',
 'The tropical forests of the Congo Basin, the world''s second-largest forest massif after the Amazon, harbor exceptional biodiversity that includes numerous viral reservoirs still poorly understood. The PREDICT-Africa surveillance network, funded by USAID and coordinated by Africa CDC, has just revealed the discovery of three novel viral families in samples collected from fruit bat populations in Cameroon and the Democratic Republic of the Congo.\n\nMetagenomic analyses, conducted at reference laboratories in Yaoundé and Kinshasa, identified genetic sequences related to henipaviruses and coronaviruses but sufficiently divergent to constitute distinct taxa. The zoonotic potential of these viruses is currently undergoing in-depth evaluation, including infectivity testing on human cell cultures.\n\nDr. Jean-Jacques Muyembe, the world-renowned Congolese virologist who co-discovered the Ebola virus, described these findings as \"an alarm signal that demands an immediate response.\" He reminded the scientific community that the majority of 21st-century pandemics originated from similar spillover events in tropical forest zones.\n\nIn response to these discoveries, the health ministries of Cameroon, DRC, Gabon, and the Republic of Congo have activated their joint rapid response protocols. Epidemiological investigation teams have been deployed to communities near the sampling areas to assess potential human exposure and strengthen syndromic surveillance.',
 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=500&fit=crop',
 'published', 0, '2026-03-10 14:00:00', 567),

(1, 1,
 'cross-border-disease-spread-sahel-corridor',
 'Propagation transfrontalière des maladies dans le corridor sahélien : défis et solutions',
 'Cross-Border Disease Spread Along the Sahel Corridor: Challenges and Solutions',
 'Le mouvement transhumant du bétail à travers le Sahel facilite la propagation de pathogènes résistants. Un nouveau cadre de coopération régionale vise à harmoniser la surveillance épidémiologique.',
 'Transhumant livestock movement across the Sahel is facilitating the spread of resistant pathogens between countries. A new regional cooperation framework aims to harmonize epidemiological surveillance across six nations.',
 'Le corridor sahélien, qui s''étend du Sénégal au Tchad, est traversé chaque année par des millions de têtes de bétail dans le cadre de mouvements transhumants traditionnels. Ces déplacements saisonniers, essentiels à l''économie pastorale, constituent également des vecteurs de propagation de maladies infectieuses à travers les frontières nationales. Une étude coordonnée par la FAO et l''Organisation mondiale de la santé animale (OMSA) documente pour la première fois l''ampleur de ce phénomène.\n\nLes chercheurs ont suivi 1 200 troupeaux équipés de traceurs GPS à travers six pays sahéliens pendant deux saisons de transhumance complètes. Les prélèvements effectués aux points de passage frontaliers ont révélé des taux alarmants de portage d''Escherichia coli productrice de bêta-lactamases à spectre étendu (BLSE), avec des prévalences variant de 35 % au Sénégal à 62 % au Niger.\n\nLe Dr Amadou Dicko, représentant de la FAO pour l''Afrique de l''Ouest, a souligné que « la transhumance est un mode de vie vital pour des millions de personnes, mais elle nécessite un accompagnement sanitaire adapté ». Il a présenté un nouveau cadre de coopération régionale qui prévoit l''harmonisation des protocoles de surveillance, la création de postes de contrôle vétérinaire mobiles et le partage de données épidémiologiques en temps réel.\n\nCe cadre, approuvé par les chefs d''État de la CEDEAO lors du sommet de Lomé en janvier 2026, bénéficie d''un financement de 28 millions d''euros de l''Union européenne et de la Banque africaine de développement. Les premiers postes de contrôle mobiles devraient être opérationnels d''ici septembre 2026.',
 'The Sahel corridor, stretching from Senegal to Chad, is traversed each year by millions of livestock as part of traditional transhumant movements. These seasonal migrations, essential to the pastoral economy, also serve as vectors for the cross-border spread of infectious diseases. A study coordinated by FAO and the World Organisation for Animal Health (WOAH) documents the scale of this phenomenon for the first time.\n\nResearchers tracked 1,200 herds equipped with GPS tracers across six Sahelian countries over two complete transhumance seasons. Samples collected at border crossing points revealed alarming rates of Extended-Spectrum Beta-Lactamase (ESBL)-producing Escherichia coli, with prevalence ranging from 35% in Senegal to 62% in Niger.\n\nDr. Amadou Dicko, FAO Representative for West Africa, emphasized that \"transhumance is a vital way of life for millions of people, but it requires appropriate health support.\" He presented a new regional cooperation framework that includes harmonized surveillance protocols, mobile veterinary checkpoints, and real-time epidemiological data sharing.\n\nThis framework, endorsed by ECOWAS heads of state at the Lomé summit in January 2026, benefits from EUR 28 million in funding from the European Union and the African Development Bank. The first mobile checkpoints are expected to be operational by September 2026.',
 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&h=500&fit=crop',
 'published', 0, '2026-04-18 09:45:00', 423),

(1, 1,
 'one-health-field-surveillance-horn-of-africa',
 'Surveillance One Health sur le terrain dans la Corne de l''Afrique : un modèle pour le continent',
 'One Health Field Surveillance in the Horn of Africa: A Model for the Continent',
 'Un programme pilote de surveillance intégrée dans la Corne de l''Afrique démontre l''efficacité de l''approche One Health pour la détection précoce des menaces zoonotiques. Les résultats dépassent les attentes initiales.',
 'A pilot integrated surveillance program in the Horn of Africa demonstrates the effectiveness of the One Health approach for early detection of zoonotic threats. Results have exceeded initial expectations after 18 months of operation.',
 'La Corne de l''Afrique — Éthiopie, Kenya, Somalie et Djibouti — est le théâtre d''un programme pilote de surveillance One Health qui pourrait redéfinir les standards de détection précoce des menaces zoonotiques sur le continent. Lancé en janvier 2025 avec le soutien du CDC Afrique, de l''OMS et de la FAO, le programme HORN-Sentinel a déployé 120 équipes de surveillance intégrée associant des médecins, des vétérinaires et des écologistes dans 45 districts prioritaires.\n\nAprès 18 mois d''opération, les résultats sont remarquables. Le programme a permis de détecter 23 événements de santé publique potentiellement dangereux, dont 8 ont été confirmés comme des menaces zoonotiques nécessitant une intervention immédiate. Le délai moyen entre la détection et la réponse a été réduit de 21 jours à seulement 4 jours, une amélioration considérable par rapport aux systèmes de surveillance conventionnels.\n\nLe Dr Ngozi Erondu, directrice du programme, a présenté les résultats lors de la Conférence internationale One Health d''Addis-Abeba. « HORN-Sentinel démontre qu''une surveillance véritablement intégrée, impliquant simultanément les secteurs de la santé humaine, animale et environnementale, est non seulement faisable mais nettement supérieure aux approches cloisonnées », a-t-elle déclaré.\n\nFort de ces résultats, le CDC Afrique a annoncé l''extension du modèle HORN-Sentinel à 15 pays supplémentaires d''ici 2028, avec un budget prévisionnel de 120 millions de dollars. L''Union africaine a également adopté une résolution appelant tous les États membres à intégrer l''approche One Health dans leurs stratégies nationales de sécurité sanitaire.',
 'The Horn of Africa — Ethiopia, Kenya, Somalia, and Djibouti — is the setting for a pilot One Health surveillance program that could redefine early detection standards for zoonotic threats across the continent. Launched in January 2025 with support from Africa CDC, WHO, and FAO, the HORN-Sentinel program has deployed 120 integrated surveillance teams combining physicians, veterinarians, and ecologists across 45 priority districts.\n\nAfter 18 months of operation, the results are remarkable. The program has detected 23 potentially dangerous public health events, of which 8 were confirmed as zoonotic threats requiring immediate intervention. The average time from detection to response was reduced from 21 days to just 4 days, a considerable improvement over conventional surveillance systems.\n\nDr. Ngozi Erondu, program director, presented the findings at the International One Health Conference in Addis Ababa. \"HORN-Sentinel demonstrates that truly integrated surveillance, simultaneously involving the human health, animal health, and environmental sectors, is not only feasible but markedly superior to siloed approaches,\" she stated.\n\nBuilding on these results, Africa CDC has announced the expansion of the HORN-Sentinel model to 15 additional countries by 2028, with a projected budget of $120 million. The African Union has also adopted a resolution calling on all member states to integrate the One Health approach into their national health security strategies.',
 'https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?w=800&h=500&fit=crop',
 'published', 0, '2026-05-22 11:30:00', 689);

-- ============================================================
-- CATEGORY 2: AMR & Résidus — 5 articles
-- ============================================================

INSERT INTO articles (category_id, author_id, slug, title_fr, title_en, excerpt_fr, excerpt_en, body_fr, body_en, cover_image, status, is_featured, published_at, views) VALUES
(2, 1,
 'antibiotic-resistance-patterns-sub-saharan-hospitals',
 'Profils de résistance aux antibiotiques dans les hôpitaux d''Afrique subsaharienne : données alarmantes',
 'Antibiotic Resistance Patterns in Sub-Saharan Hospitals: Alarming Data',
 'Une méta-analyse portant sur 200 hôpitaux de 15 pays africains révèle des taux de résistance aux carbapénèmes supérieurs à 30 % dans certaines régions. L''urgence d''agir est désormais indiscutable.',
 'A meta-analysis covering 200 hospitals across 15 African countries reveals carbapenem resistance rates exceeding 30% in some regions. The urgency for action is now indisputable as last-resort antibiotics lose their effectiveness.',
 'La résistance aux antimicrobiens (RAM) dans les établissements de santé d''Afrique subsaharienne atteint des niveaux critiques selon une méta-analyse publiée dans The Lancet Infectious Diseases. L''étude, qui a compilé les données de susceptibilité antimicrobienne de 200 hôpitaux répartis dans 15 pays, révèle que les taux de résistance aux carbapénèmes — les antibiotiques de dernier recours — dépassent 30 % dans les établissements de soins de la région des Grands Lacs et de l''Afrique de l''Ouest côtière.\n\nLes pathogènes les plus préoccupants identifiés par l''étude incluent Klebsiella pneumoniae résistante aux carbapénèmes (prévalence de 34 % en moyenne), Acinetobacter baumannii multirésistant (45 % des isolats dans les unités de soins intensifs) et Staphylococcus aureus résistant à la méticilline (SARM, 28 % des isolats hospitaliers). Ces chiffres placent l''Afrique subsaharienne parmi les régions les plus affectées au monde.\n\nLe professeur Yewande Alimi, responsable du programme RAM au CDC Afrique, a qualifié ces résultats de « crise silencieuse qui tue plus que le VIH et le paludisme réunis dans certains contextes hospitaliers ». Elle a souligné que le manque de laboratoires de microbiologie clinique — moins de 20 % des hôpitaux de district en disposent — contribue à sous-estimer l''ampleur réelle du problème.\n\nL''étude recommande la mise en place urgente de programmes de gestion des antimicrobiens dans tous les hôpitaux de référence, le renforcement des capacités de diagnostic microbiologique et l''adoption de protocoles de prévention des infections nosocomiales adaptés aux contextes à ressources limitées. Un fonds de 75 millions de dollars a été proposé pour soutenir ces interventions sur une période de cinq ans.',
 'Antimicrobial resistance (AMR) in sub-Saharan African healthcare facilities has reached critical levels according to a meta-analysis published in The Lancet Infectious Diseases. The study, which compiled antimicrobial susceptibility data from 200 hospitals across 15 countries, reveals that carbapenem resistance rates — for last-resort antibiotics — exceed 30% in healthcare facilities in the Great Lakes region and coastal West Africa.\n\nThe most concerning pathogens identified by the study include carbapenem-resistant Klebsiella pneumoniae (34% average prevalence), multidrug-resistant Acinetobacter baumannii (45% of isolates in intensive care units), and methicillin-resistant Staphylococcus aureus (MRSA, 28% of hospital isolates). These figures place sub-Saharan Africa among the most affected regions globally.\n\nProfessor Yewande Alimi, head of the AMR program at Africa CDC, described these findings as \"a silent crisis that kills more than HIV and malaria combined in some hospital settings.\" She emphasized that the lack of clinical microbiology laboratories — fewer than 20% of district hospitals have them — contributes to underestimating the true scale of the problem.\n\nThe study recommends the urgent implementation of antimicrobial stewardship programs in all referral hospitals, strengthening microbiological diagnostic capacity, and adopting infection prevention protocols adapted to resource-limited settings. A $75 million fund has been proposed to support these interventions over a five-year period.',
 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=800&h=500&fit=crop',
 'published', 1, '2026-01-28 07:00:00', 1045),

(2, 1,
 'antibiotic-residue-testing-livestock-products',
 'Détection des résidus d''antibiotiques dans les produits d''élevage : un réseau de laboratoires panafricain',
 'Antibiotic Residue Testing in Livestock Products: A Pan-African Laboratory Network',
 'Le nouveau réseau AFRI-ResidueLab, regroupant 30 laboratoires dans 22 pays, standardise pour la première fois les méthodes de détection des résidus d''antibiotiques dans la viande, le lait et les œufs sur le continent.',
 'The new AFRI-ResidueLab network, uniting 30 laboratories across 22 countries, is standardizing antibiotic residue detection methods in meat, milk, and eggs across the continent for the first time.',
 'La contamination des produits alimentaires d''origine animale par des résidus d''antibiotiques constitue un facteur majeur de développement de la résistance antimicrobienne en Afrique. Pour lutter contre ce phénomène, un réseau panafricain de laboratoires spécialisés — AFRI-ResidueLab — a été officiellement lancé lors de la Conférence sur la sécurité alimentaire de Kigali en février 2026.\n\nLe réseau regroupe 30 laboratoires répartis dans 22 pays africains, équipés de technologies de pointe incluant la chromatographie liquide haute performance (HPLC) et la spectrométrie de masse. Pour la première fois, des protocoles harmonisés de détection des résidus d''antibiotiques dans la viande, le lait et les œufs sont appliqués de manière uniforme à travers le continent, permettant des comparaisons fiables entre pays.\n\nLes premiers résultats du réseau sont préoccupants : sur 5 000 échantillons analysés au cours du premier trimestre 2026, 23 % contenaient des résidus d''antibiotiques dépassant les limites maximales fixées par le Codex Alimentarius. Les tétracyclines et les fluoroquinolones représentent les classes d''antibiotiques les plus fréquemment détectées, reflétant leur utilisation massive dans l''élevage intensif et semi-intensif.\n\nLe Dr Bernadette Abela-Ridder, responsable du programme RAM à l''OMS, a salué cette initiative comme « une étape fondamentale vers la traçabilité des antimicrobiens dans la chaîne alimentaire africaine ». Le réseau prévoit d''étendre ses capacités d''analyse à 50 laboratoires d''ici 2028, avec l''objectif de couvrir 90 % des pays membres de l''Union africaine.',
 'Contamination of animal-source food products with antibiotic residues is a major driver of antimicrobial resistance development in Africa. To combat this phenomenon, a pan-African network of specialized laboratories — AFRI-ResidueLab — was officially launched at the Kigali Food Safety Conference in February 2026.\n\nThe network brings together 30 laboratories across 22 African countries, equipped with cutting-edge technologies including High-Performance Liquid Chromatography (HPLC) and mass spectrometry. For the first time, harmonized protocols for detecting antibiotic residues in meat, milk, and eggs are being applied uniformly across the continent, enabling reliable cross-country comparisons.\n\nThe network''s initial findings are concerning: of 5,000 samples analyzed during the first quarter of 2026, 23% contained antibiotic residues exceeding the maximum limits set by the Codex Alimentarius. Tetracyclines and fluoroquinolones are the most frequently detected antibiotic classes, reflecting their massive use in intensive and semi-intensive livestock production.\n\nDr. Bernadette Abela-Ridder, head of the AMR program at WHO, hailed this initiative as \"a fundamental step toward antimicrobial traceability in the African food chain.\" The network plans to expand its analytical capacity to 50 laboratories by 2028, with the goal of covering 90% of African Union member states.',
 'https://images.unsplash.com/photo-1579165466991-467135ad3110?w=800&h=500&fit=crop',
 'published', 0, '2026-02-20 13:00:00', 612),

(2, 1,
 'hospital-acquired-infections-neonatal-units-africa',
 'Infections nosocomiales dans les unités néonatales africaines : la RAM comme menace invisible',
 'Hospital-Acquired Infections in African Neonatal Units: AMR as an Invisible Threat',
 'Une étude multicentrique dans 12 pays révèle que 40 % des infections néonatales hospitalières sont causées par des bactéries multirésistantes. Les nouveau-nés africains paient le prix le plus élevé de la crise de la RAM.',
 'A multicenter study across 12 countries reveals that 40% of hospital-acquired neonatal infections are caused by multidrug-resistant bacteria. African newborns are paying the highest price of the AMR crisis.',
 'Les unités de soins néonatals en Afrique subsaharienne font face à une crise silencieuse mais dévastatrice : la résistance aux antimicrobiens. Une étude multicentrique menée dans 60 unités néonatales de 12 pays, publiée dans le New England Journal of Medicine, révèle que 40 % des infections nosocomiales chez les nouveau-nés sont causées par des bactéries résistantes à au moins trois classes d''antibiotiques.\n\nL''étude, baptisée NeoAMR-Africa, a suivi 8 500 nouveau-nés hospitalisés sur une période de deux ans. Les résultats montrent un taux de mortalité attribuable aux infections multirésistantes de 18 %, soit trois fois supérieur à celui observé dans les infections sensibles aux antibiotiques. Les pathogènes les plus mortels incluent Klebsiella pneumoniae productrice de carbapénémases et Acinetobacter baumannii panrésistant.\n\nLe professeur Iruka Okeke, microbiologiste à l''Université d''Ibadan et co-autrice de l''étude, a déclaré que « chaque jour, des nouveau-nés africains meurent d''infections qui seraient facilement traitables avec des antibiotiques efficaces. C''est une injustice sanitaire fondamentale ». Elle a plaidé pour l''intégration de la surveillance de la RAM dans les programmes de santé maternelle et néonatale.\n\nParmi les recommandations clés de l''étude figurent le renforcement des pratiques d''hygiène hospitalière, la mise en place de comités de gestion des antibiotiques dans chaque maternité de référence et l''investissement dans la formation continue du personnel soignant. L''OMS a annoncé un programme de soutien technique dédié pour 25 pays prioritaires.',
 'Neonatal care units in sub-Saharan Africa face a silent but devastating crisis: antimicrobial resistance. A multicenter study conducted across 60 neonatal units in 12 countries, published in the New England Journal of Medicine, reveals that 40% of hospital-acquired infections in newborns are caused by bacteria resistant to at least three classes of antibiotics.\n\nThe study, named NeoAMR-Africa, followed 8,500 hospitalized newborns over a two-year period. Results show an attributable mortality rate from multidrug-resistant infections of 18%, three times higher than that observed in antibiotic-susceptible infections. The deadliest pathogens include carbapenemase-producing Klebsiella pneumoniae and pandrug-resistant Acinetobacter baumannii.\n\nProfessor Iruka Okeke, microbiologist at the University of Ibadan and study co-author, stated that \"every day, African newborns die from infections that would be easily treatable with effective antibiotics. This is a fundamental health injustice.\" She advocated for integrating AMR surveillance into maternal and neonatal health programs.\n\nKey recommendations from the study include strengthening hospital hygiene practices, establishing antibiotic stewardship committees in every referral maternity unit, and investing in continuous training for healthcare workers. WHO has announced a dedicated technical support program for 25 priority countries.',
 'https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=800&h=500&fit=crop',
 'published', 0, '2026-03-28 08:15:00', 978),

(2, 1,
 'pharmaceutical-contamination-african-waterways',
 'Contamination pharmaceutique des cours d''eau africains : un accélérateur méconnu de la RAM',
 'Pharmaceutical Contamination of African Waterways: An Underrecognized AMR Accelerator',
 'Des concentrations record d''antibiotiques détectées dans les rivières proches des zones industrielles pharmaceutiques en Afrique de l''Est et du Nord. Les bactéries environnementales deviennent des réservoirs de gènes de résistance.',
 'Record concentrations of antibiotics detected in rivers near pharmaceutical industrial zones in East and North Africa. Environmental bacteria are becoming reservoirs of resistance genes that can transfer to human pathogens.',
 'La pollution pharmaceutique des cours d''eau africains émerge comme un facteur critique mais sous-étudié dans l''accélération de la résistance aux antimicrobiens. Une étude publiée dans Nature Water, menée par des chercheurs de l''Université de Nairobi et de l''Institut national de la santé publique du Maroc, a mesuré les concentrations d''antibiotiques dans 45 rivières et plans d''eau à travers 10 pays africains.\n\nLes résultats sont alarmants : dans les zones situées en aval des complexes industriels pharmaceutiques au Kenya, en Égypte et au Maroc, les concentrations de ciprofloxacine et d''azithromycine dépassent respectivement 100 et 50 fois les seuils de risque environnemental établis par l''Agence européenne des médicaments. Ces niveaux de contamination créent une pression de sélection intense favorisant l''émergence et la propagation de bactéries résistantes dans l''environnement.\n\nLes analyses métagénomiques des sédiments fluviaux ont révélé une diversité exceptionnelle de gènes de résistance aux antibiotiques, y compris des gènes mcr de résistance à la colistine et des gènes blaNDM de résistance aux carbapénèmes. « Ces gènes ne restent pas confinés dans l''environnement », a averti le Dr Samuel Kariuki, directeur de recherche au KEMRI. « Ils se transfèrent horizontalement aux bactéries pathogènes humaines, créant un pipeline continu de résistance. »\n\nL''étude appelle à une réglementation urgente des effluents pharmaceutiques industriels, à la mise en place de systèmes de traitement des eaux usées adaptés et à l''intégration de la surveillance environnementale de la RAM dans les plans d''action nationaux. Plusieurs pays ont déjà commencé à réviser leurs normes de rejet industriel à la lumière de ces données.',
 'Pharmaceutical pollution of African waterways is emerging as a critical but understudied driver in the acceleration of antimicrobial resistance. A study published in Nature Water, conducted by researchers from the University of Nairobi and Morocco''s National Institute of Public Health, measured antibiotic concentrations in 45 rivers and water bodies across 10 African countries.\n\nThe findings are alarming: in areas downstream of pharmaceutical industrial complexes in Kenya, Egypt, and Morocco, concentrations of ciprofloxacin and azithromycin exceed the environmental risk thresholds established by the European Medicines Agency by 100-fold and 50-fold, respectively. These contamination levels create intense selection pressure favoring the emergence and spread of resistant bacteria in the environment.\n\nMetagenomic analyses of river sediments revealed an exceptional diversity of antibiotic resistance genes, including mcr genes for colistin resistance and blaNDM genes for carbapenem resistance. \"These genes do not remain confined to the environment,\" warned Dr. Samuel Kariuki, research director at KEMRI. \"They transfer horizontally to human pathogenic bacteria, creating a continuous resistance pipeline.\"\n\nThe study calls for urgent regulation of pharmaceutical industrial effluents, implementation of appropriate wastewater treatment systems, and integration of environmental AMR surveillance into national action plans. Several countries have already begun revising their industrial discharge standards in light of these findings.',
 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?w=800&h=500&fit=crop',
 'published', 0, '2026-05-05 10:00:00', 356),

(2, 1,
 'resistance-gene-tracking-across-african-borders',
 'Traçage des gènes de résistance à travers les frontières africaines : le projet GenomAMR-Africa',
 'Resistance Gene Tracking Across African Borders: The GenomAMR-Africa Project',
 'Le projet GenomAMR-Africa utilise le séquençage génomique pour cartographier la propagation des gènes de résistance aux antibiotiques à travers le continent. Les premiers résultats révèlent des corridors de transmission inattendus.',
 'The GenomAMR-Africa project uses whole-genome sequencing to map the spread of antibiotic resistance genes across the continent. Initial results reveal unexpected transmission corridors linked to trade and migration routes.',
 'Le projet GenomAMR-Africa, lancé en 2025 sous l''égide du CDC Afrique et du Wellcome Sanger Institute, représente la plus ambitieuse initiative de surveillance génomique de la résistance aux antimicrobiens jamais entreprise sur le continent africain. En utilisant le séquençage du génome entier (WGS), le projet vise à cartographier la propagation des gènes de résistance aux antibiotiques à travers les frontières nationales et à identifier les corridors de transmission prioritaires.\n\nAu cours de sa première année d''opération, GenomAMR-Africa a séquencé plus de 15 000 isolats bactériens collectés dans 28 pays africains. Les analyses phylogénétiques ont révélé des schémas de propagation inattendus : les gènes de résistance aux carbapénèmes de type NDM-5, initialement identifiés en Afrique du Nord, se sont propagés vers l''Afrique de l''Ouest via des corridors commerciaux traversant le Sahara, plutôt que par les voies de migration nord-sud traditionnellement suspectées.\n\nLe Dr Iruka Okeke, conseillère scientifique du projet, a expliqué que « la résistance ne respecte pas les frontières. Notre approche génomique nous permet de voir, pour la première fois, comment les gènes de résistance voyagent à travers le continent, souvent en suivant les routes commerciales et les flux migratoires ». Elle a souligné l''importance de ces données pour orienter les interventions de santé publique.\n\nLe projet a également mis en place une plateforme de partage de données génomiques en accès libre, permettant aux chercheurs et aux décideurs de 54 pays africains de visualiser en temps réel la distribution géographique des principaux déterminants de résistance. Cette transparence sans précédent est saluée par la communauté scientifique internationale comme un modèle de collaboration Sud-Sud.',
 'The GenomAMR-Africa project, launched in 2025 under the auspices of Africa CDC and the Wellcome Sanger Institute, represents the most ambitious genomic surveillance initiative for antimicrobial resistance ever undertaken on the African continent. Using whole-genome sequencing (WGS), the project aims to map the spread of antibiotic resistance genes across national borders and identify priority transmission corridors.\n\nIn its first year of operation, GenomAMR-Africa sequenced over 15,000 bacterial isolates collected from 28 African countries. Phylogenetic analyses revealed unexpected propagation patterns: NDM-5 type carbapenem resistance genes, initially identified in North Africa, spread to West Africa via trans-Saharan trade corridors rather than through the traditionally suspected north-south migration routes.\n\nDr. Iruka Okeke, scientific advisor to the project, explained that \"resistance does not respect borders. Our genomic approach allows us to see, for the first time, how resistance genes travel across the continent, often following trade routes and migration flows.\" She emphasized the importance of these data for guiding public health interventions.\n\nThe project has also established an open-access genomic data sharing platform, enabling researchers and policymakers from 54 African countries to visualize the geographic distribution of key resistance determinants in real time. This unprecedented transparency is hailed by the international scientific community as a model for South-South collaboration.',
 'https://images.unsplash.com/photo-1582719471384-894fbb16564e?w=800&h=500&fit=crop',
 'published', 0, '2026-06-12 15:30:00', 287);

-- ============================================================
-- CATEGORY 3: Politique & Sécurité commerciale — 5 articles
-- ============================================================

INSERT INTO articles (category_id, author_id, slug, title_fr, title_en, excerpt_fr, excerpt_en, body_fr, body_en, cover_image, status, is_featured, published_at, views) VALUES
(3, 1,
 'who-au-joint-framework-antimicrobial-governance',
 'Cadre conjoint OMS-UA pour la gouvernance des antimicrobiens : une nouvelle ère réglementaire',
 'WHO-AU Joint Framework for Antimicrobial Governance: A New Regulatory Era',
 'L''OMS et l''Union africaine signent un cadre historique de gouvernance des antimicrobiens qui établit des normes contraignantes pour 55 pays africains. Le cadre prévoit des mécanismes de suivi et de responsabilité sans précédent.',
 'WHO and the African Union sign a landmark antimicrobial governance framework establishing binding standards for 55 African countries. The framework includes unprecedented monitoring and accountability mechanisms.',
 'L''Organisation mondiale de la Santé et l''Union africaine ont franchi une étape historique en signant le premier cadre contraignant de gouvernance des antimicrobiens pour le continent africain. Adopté lors du Sommet extraordinaire de l''UA sur la santé à Addis-Abeba en mars 2026, ce cadre établit des normes minimales que les 55 États membres s''engagent à respecter en matière de réglementation, de surveillance et d''utilisation des antimicrobiens.\n\nLe cadre repose sur quatre piliers fondamentaux : la réglementation de la vente d''antibiotiques (interdiction de la vente sans ordonnance d''ici 2028), la surveillance intégrée de la RAM (obligation de rapporter les données de susceptibilité antimicrobienne au CDC Afrique), la gestion des antimicrobiens en milieu hospitalier (mise en place obligatoire de comités de gestion dans tous les hôpitaux de référence) et la réduction de l''utilisation des antibiotiques comme promoteurs de croissance en élevage.\n\nLe Dr Tedros Adhanom Ghebreyesus, Directeur général de l''OMS, a qualifié cet accord de « moment décisif dans la lutte mondiale contre la RAM ». Il a souligné que « l''Afrique montre au monde qu''il est possible de construire un consensus politique fort autour de la gouvernance des antimicrobiens, même dans des contextes de ressources limitées ».\n\nUn mécanisme d''évaluation par les pairs, inspiré du Mécanisme africain d''évaluation par les pairs (MAEP), sera mis en place pour suivre la mise en œuvre du cadre. Les pays qui ne respecteront pas les délais fixés feront l''objet de recommandations publiques, créant ainsi une pression diplomatique positive. Le premier cycle d''évaluation est prévu pour 2028.',
 'The World Health Organization and the African Union have reached a historic milestone by signing the first binding antimicrobial governance framework for the African continent. Adopted at the AU Extraordinary Summit on Health in Addis Ababa in March 2026, this framework establishes minimum standards that all 55 member states commit to upholding regarding antimicrobial regulation, surveillance, and use.\n\nThe framework rests on four fundamental pillars: regulation of antibiotic sales (ban on over-the-counter sales by 2028), integrated AMR surveillance (mandatory reporting of antimicrobial susceptibility data to Africa CDC), hospital antimicrobial stewardship (mandatory establishment of stewardship committees in all referral hospitals), and reduction of antibiotic use as growth promoters in livestock production.\n\nDr. Tedros Adhanom Ghebreyesus, WHO Director-General, described this agreement as \"a decisive moment in the global fight against AMR.\" He emphasized that \"Africa is showing the world that it is possible to build strong political consensus around antimicrobial governance, even in resource-limited settings.\"\n\nA peer review mechanism, inspired by the African Peer Review Mechanism (APRM), will be established to monitor framework implementation. Countries that fail to meet the set deadlines will be subject to public recommendations, creating positive diplomatic pressure. The first evaluation cycle is planned for 2028.',
 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800&h=500&fit=crop',
 'published', 1, '2026-03-15 09:00:00', 1198),

(3, 1,
 'trade-regulations-antibiotic-residues-afcfta',
 'Réglementations commerciales sur les résidus d''antibiotiques dans le cadre de la ZLECAf',
 'Trade Regulations on Antibiotic Residues Under the AfCFTA Framework',
 'La Zone de libre-échange continentale africaine intègre pour la première fois des normes harmonisées sur les résidus d''antibiotiques dans les produits alimentaires échangés entre pays membres.',
 'The African Continental Free Trade Area integrates harmonized standards on antibiotic residues in food products traded between member countries for the first time.',
 'La mise en œuvre de la Zone de libre-échange continentale africaine (ZLECAf) soulève des questions cruciales en matière de sécurité sanitaire des aliments, notamment concernant les résidus d''antibiotiques dans les produits d''origine animale. Lors de la 5e session ordinaire du Conseil des ministres du commerce de la ZLECAf, tenue à Accra en avril 2026, un protocole additionnel sur les normes sanitaires relatives aux résidus d''antimicrobiens a été adopté à l''unanimité.\n\nCe protocole établit des limites maximales de résidus (LMR) harmonisées pour 15 classes d''antibiotiques dans la viande, le lait, les œufs et le miel échangés entre pays membres. Les LMR adoptées sont alignées sur les normes du Codex Alimentarius, avec des adaptations spécifiques pour les systèmes de production africains. Un laboratoire de référence continental, basé à Kampala, sera chargé de l''arbitrage en cas de litiges commerciaux liés aux résidus.\n\nLe Secrétaire général de la ZLECAf, Wamkele Mene, a souligné que « le commerce intra-africain ne peut prospérer que si les consommateurs ont confiance dans la sécurité des produits qu''ils achètent. Ce protocole est un investissement dans la crédibilité de notre zone de libre-échange ». Il a également annoncé un programme de renforcement des capacités pour les laboratoires nationaux de contrôle qualité.\n\nLes analystes estiment que ce protocole pourrait affecter jusqu''à 12 milliards de dollars de commerce alimentaire intra-africain annuel. Les pays exportateurs devront adapter leurs chaînes de production pour se conformer aux nouvelles normes, ce qui représente à la fois un défi et une opportunité de modernisation du secteur agroalimentaire continental.',
 'The implementation of the African Continental Free Trade Area (AfCFTA) raises crucial questions regarding food safety, particularly concerning antibiotic residues in animal-source products. During the 5th Ordinary Session of the AfCFTA Council of Trade Ministers, held in Accra in April 2026, an additional protocol on sanitary standards for antimicrobial residues was unanimously adopted.\n\nThis protocol establishes harmonized Maximum Residue Limits (MRLs) for 15 classes of antibiotics in meat, milk, eggs, and honey traded between member countries. The adopted MRLs are aligned with Codex Alimentarius standards, with specific adaptations for African production systems. A continental reference laboratory, based in Kampala, will be responsible for arbitration in trade disputes related to residues.\n\nAfCFTA Secretary-General Wamkele Mene emphasized that \"intra-African trade can only thrive if consumers trust the safety of the products they buy. This protocol is an investment in the credibility of our free trade area.\" He also announced a capacity-building program for national quality control laboratories.\n\nAnalysts estimate that this protocol could affect up to $12 billion in annual intra-African food trade. Exporting countries will need to adapt their production chains to comply with the new standards, representing both a challenge and an opportunity for modernizing the continental agri-food sector.',
 'https://images.unsplash.com/photo-1576671081837-49000212a370?w=800&h=500&fit=crop',
 'published', 0, '2026-04-10 11:00:00', 534),

(3, 1,
 'antimicrobial-stewardship-programs-scaling-up',
 'Programmes de gestion des antimicrobiens : passage à l''échelle dans 30 pays africains',
 'Antimicrobial Stewardship Programs: Scaling Up Across 30 African Countries',
 'Le programme Fleming Fund accélère le déploiement de programmes de gestion des antimicrobiens dans 30 pays africains. Les premiers résultats montrent une réduction de 15 % de la consommation inappropriée d''antibiotiques.',
 'The Fleming Fund is accelerating the deployment of antimicrobial stewardship programs across 30 African countries. Early results show a 15% reduction in inappropriate antibiotic consumption in participating hospitals.',
 'Les programmes de gestion des antimicrobiens (PGA) — conçus pour optimiser l''utilisation des antibiotiques et réduire l''émergence de résistances — connaissent un déploiement sans précédent en Afrique grâce au soutien du Fleming Fund, une initiative britannique dotée de 265 millions de livres sterling. En juin 2026, 30 pays africains ont intégré le programme, contre seulement 8 en 2023.\n\nLes PGA mis en place dans les hôpitaux participants reposent sur une approche multidisciplinaire associant infectiologues, pharmaciens, microbiologistes et gestionnaires hospitaliers. Les interventions incluent l''élaboration de guides thérapeutiques adaptés au contexte local, la mise en place de systèmes d''approbation préalable pour les antibiotiques à large spectre, la formation continue du personnel prescripteur et l''analyse régulière des données de consommation d''antibiotiques.\n\nLes résultats préliminaires, présentés lors de la Conférence mondiale sur la RAM à Genève, sont encourageants. Dans les 150 hôpitaux pilotes, la consommation inappropriée d''antibiotiques a diminué de 15 % en moyenne, tandis que la durée médiane des traitements antibiotiques a été réduite de 10 à 7 jours sans impact négatif sur les résultats cliniques. Les économies réalisées sur les achats d''antibiotiques ont permis de réinvestir dans le diagnostic microbiologique.\n\nLe Dr Hanan Balkhy, Sous-Directrice générale de l''OMS pour la résistance aux antimicrobiens, a salué ces progrès tout en rappelant que « le passage à l''échelle reste le plus grand défi. Nous devons transformer ces succès hospitaliers en politiques nationales durables ». Le Fleming Fund a annoncé une extension de son financement jusqu''en 2030.',
 'Antimicrobial stewardship programs (ASPs) — designed to optimize antibiotic use and reduce the emergence of resistance — are experiencing unprecedented deployment across Africa thanks to support from the Fleming Fund, a British initiative with GBP 265 million in funding. By June 2026, 30 African countries have joined the program, up from just 8 in 2023.\n\nThe ASPs implemented in participating hospitals are based on a multidisciplinary approach involving infectious disease specialists, pharmacists, microbiologists, and hospital managers. Interventions include developing treatment guidelines adapted to local contexts, establishing prior authorization systems for broad-spectrum antibiotics, continuous training for prescribing staff, and regular analysis of antibiotic consumption data.\n\nPreliminary results, presented at the Global AMR Conference in Geneva, are encouraging. In the 150 pilot hospitals, inappropriate antibiotic consumption decreased by an average of 15%, while median antibiotic treatment duration was reduced from 10 to 7 days with no negative impact on clinical outcomes. Savings on antibiotic purchases have been reinvested in microbiological diagnostics.\n\nDr. Hanan Balkhy, WHO Assistant Director-General for Antimicrobial Resistance, praised this progress while noting that \"scaling up remains the greatest challenge. We must transform these hospital-level successes into sustainable national policies.\" The Fleming Fund has announced an extension of its funding through 2030.',
 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=800&h=500&fit=crop',
 'published', 0, '2026-05-01 14:30:00', 445),

(3, 1,
 'global-fund-amr-africa-billion-dollar-pledge',
 'Le Fonds mondial contre la RAM en Afrique : un engagement d''un milliard de dollars',
 'Global Fund for AMR in Africa: A Billion-Dollar Pledge',
 'Lors du Sommet du G20 à Cape Town, les donateurs internationaux s''engagent à mobiliser un milliard de dollars pour lutter contre la RAM en Afrique sur la période 2026-2031. Un moment charnière pour le financement de la santé mondiale.',
 'At the G20 Summit in Cape Town, international donors pledge to mobilize one billion dollars to combat AMR in Africa over the 2026-2031 period. A pivotal moment for global health financing.',
 'Le Sommet du G20, tenu pour la première fois sur le continent africain à Cape Town en mai 2026, a été marqué par un engagement financier historique en faveur de la lutte contre la résistance aux antimicrobiens en Afrique. Un consortium de donateurs comprenant l''Union européenne, les États-Unis, le Royaume-Uni, le Japon et la Fondation Bill & Melinda Gates a annoncé la mobilisation d''un milliard de dollars sur cinq ans (2026-2031) pour soutenir les efforts africains contre la RAM.\n\nCet engagement, le plus important jamais consacré spécifiquement à la RAM en Afrique, sera canalisé à travers un mécanisme de financement innovant géré conjointement par le CDC Afrique, l''OMS et la Banque mondiale. Les fonds seront répartis selon quatre priorités : le renforcement des systèmes de surveillance (30 %), l''amélioration de l''accès aux diagnostics (25 %), le soutien aux programmes de gestion des antimicrobiens (25 %) et la recherche-développement de nouvelles solutions (20 %).\n\nLe président de l''Union africaine, Moussa Faki Mahamat, a qualifié cet engagement de « reconnaissance longtemps attendue que la RAM en Afrique est un problème mondial qui nécessite des solutions mondiales ». Il a souligné que l''Afrique supporte 24 % du fardeau mondial de la RAM tout en ne recevant que 3 % du financement mondial consacré à cette menace.\n\nLes organisations de la société civile ont accueilli favorablement cette annonce tout en soulignant la nécessité de mécanismes de transparence robustes. « L''argent est nécessaire mais pas suffisant », a déclaré le Dr Manica Balasegaram, directeur du Partenariat mondial pour la recherche-développement en antibiothérapie (GARDP). « Ce qui compte, c''est comment ces fonds seront dépensés et qui en bénéficiera réellement. »',
 'The G20 Summit, held for the first time on the African continent in Cape Town in May 2026, was marked by a historic financial commitment to combating antimicrobial resistance in Africa. A donor consortium including the European Union, the United States, the United Kingdom, Japan, and the Bill & Melinda Gates Foundation announced the mobilization of one billion dollars over five years (2026-2031) to support African efforts against AMR.\n\nThis commitment, the largest ever dedicated specifically to AMR in Africa, will be channeled through an innovative financing mechanism jointly managed by Africa CDC, WHO, and the World Bank. Funds will be distributed across four priorities: strengthening surveillance systems (30%), improving access to diagnostics (25%), supporting antimicrobial stewardship programs (25%), and research and development of new solutions (20%).\n\nAfrican Union Chairperson Moussa Faki Mahamat described this commitment as \"a long-overdue recognition that AMR in Africa is a global problem requiring global solutions.\" He emphasized that Africa bears 24% of the global AMR burden while receiving only 3% of global funding dedicated to this threat.\n\nCivil society organizations welcomed the announcement while stressing the need for robust transparency mechanisms. \"Money is necessary but not sufficient,\" said Dr. Manica Balasegaram, director of the Global Antibiotic Research and Development Partnership (GARDP). \"What matters is how these funds will be spent and who will truly benefit.\"',
 'https://images.unsplash.com/photo-1551076805-e1869033e561?w=800&h=500&fit=crop',
 'published', 0, '2026-05-20 08:00:00', 892),

(3, 1,
 'international-cooperation-amr-south-south-partnerships',
 'Coopération internationale contre la RAM : l''essor des partenariats Sud-Sud',
 'International Cooperation on AMR: The Rise of South-South Partnerships',
 'L''Inde, le Brésil et l''Afrique du Sud lancent une initiative trilatérale de coopération technique sur la RAM. Ce partenariat Sud-Sud vise à partager les technologies et les bonnes pratiques entre pays à revenu faible et intermédiaire.',
 'India, Brazil, and South Africa launch a trilateral technical cooperation initiative on AMR. This South-South partnership aims to share technologies and best practices among low- and middle-income countries.',
 'La coopération Sud-Sud en matière de lutte contre la résistance aux antimicrobiens connaît un essor remarquable, illustré par le lancement de l''Initiative IBSA-AMR (Inde-Brésil-Afrique du Sud) lors du Forum IBSA de Pretoria en juin 2026. Cette initiative trilatérale vise à partager les technologies, les expertises et les bonnes pratiques entre pays à revenu faible et intermédiaire, qui supportent collectivement plus de 70 % du fardeau mondial de la RAM.\n\nL''Initiative IBSA-AMR s''articule autour de trois axes prioritaires : le transfert de technologies de diagnostic rapide développées en Inde vers les laboratoires africains et latino-américains, le partage des protocoles brésiliens de gestion des antimicrobiens en agriculture avec les pays membres de l''Union africaine et la mise en commun des données de surveillance génomique à travers une plateforme numérique partagée.\n\nLe ministre sud-africain de la Santé, Dr Joe Phaahla, a souligné que « les pays du Sud global partagent des défis similaires face à la RAM : des systèmes de santé sous pression, un accès limité aux diagnostics et une utilisation non réglementée des antibiotiques. Nos solutions doivent être co-construites, pas importées ». Il a annoncé la création d''un centre d''excellence conjoint basé à Johannesburg.\n\nL''initiative a également reçu le soutien technique de l''OMS et du Programme des Nations Unies pour le développement (PNUD). Un fonds initial de 50 millions de dollars, financé à parts égales par les trois pays fondateurs, soutiendra les activités pendant les trois premières années. D''autres pays, dont le Nigeria, l''Indonésie et le Mexique, ont exprimé leur intérêt pour rejoindre l''initiative.',
 'South-South cooperation in combating antimicrobial resistance is experiencing a remarkable surge, exemplified by the launch of the IBSA-AMR Initiative (India-Brazil-South Africa) at the IBSA Forum in Pretoria in June 2026. This trilateral initiative aims to share technologies, expertise, and best practices among low- and middle-income countries, which collectively bear more than 70% of the global AMR burden.\n\nThe IBSA-AMR Initiative is organized around three priority areas: transfer of rapid diagnostic technologies developed in India to African and Latin American laboratories, sharing of Brazilian antimicrobial stewardship protocols in agriculture with African Union member countries, and pooling of genomic surveillance data through a shared digital platform.\n\nSouth African Health Minister Dr. Joe Phaahla emphasized that \"Global South countries share similar challenges in facing AMR: health systems under pressure, limited access to diagnostics, and unregulated antibiotic use. Our solutions must be co-created, not imported.\" He announced the establishment of a joint center of excellence based in Johannesburg.\n\nThe initiative has also received technical support from WHO and the United Nations Development Programme (UNDP). An initial fund of $50 million, financed equally by the three founding countries, will support activities during the first three years. Other countries, including Nigeria, Indonesia, and Mexico, have expressed interest in joining the initiative.',
 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop',
 'published', 0, '2026-06-18 12:00:00', 178);

-- ============================================================
-- CATEGORY 4: Tech & Innovation — 5 articles
-- ============================================================

INSERT INTO articles (category_id, author_id, slug, title_fr, title_en, excerpt_fr, excerpt_en, body_fr, body_en, cover_image, status, is_featured, published_at, views) VALUES
(4, 1,
 'ai-ml-amr-surveillance-african-health-systems',
 'Intelligence artificielle et surveillance de la RAM dans les systèmes de santé africains',
 'AI and Machine Learning for AMR Surveillance in African Health Systems',
 'Un consortium de centres de recherche africains déploie des modèles d''apprentissage automatique capables de prédire les schémas de résistance aux antibiotiques avec une précision de 89 %. Ces outils pourraient transformer la prescription empirique.',
 'A consortium of African research centers is deploying machine learning models capable of predicting antibiotic resistance patterns with 89% accuracy. These tools could transform empirical prescribing in resource-limited settings.',
 'L''intelligence artificielle s''impose comme un outil transformateur dans la surveillance de la résistance aux antimicrobiens en Afrique. Un consortium regroupant l''Université du Cap, le KEMRI au Kenya, l''Université d''Ibadan au Nigeria et l''Institut Pasteur de Madagascar a développé et validé des modèles d''apprentissage automatique capables de prédire les profils de résistance aux antibiotiques avec une précision sans précédent de 89 %.\n\nLes modèles, baptisés AfriAMR-Predict, utilisent des réseaux de neurones profonds entraînés sur une base de données de plus de 2 millions d''antibiogrammes collectés dans 200 hôpitaux africains entre 2018 et 2025. En intégrant des variables cliniques (âge, diagnostic, antécédents d''hospitalisation), géographiques (région, milieu urbain/rural) et temporelles (saison, tendances épidémiologiques), les modèles peuvent recommander le traitement antibiotique le plus approprié avant même que les résultats de culture ne soient disponibles.\n\nLe professeur Tulio de Oliveira, bio-informaticien à l''Université du Cap et architecte principal du projet, a expliqué que « dans un continent où moins de 10 % des prescriptions d''antibiotiques sont guidées par un antibiogramme, l''IA peut combler ce déficit diagnostique de manière considérable ». Il a ajouté que les modèles sont conçus pour fonctionner sur des smartphones avec une connexion Internet limitée.\n\nUne étude pilote menée dans 20 hôpitaux kenyans a montré que l''utilisation d''AfriAMR-Predict a réduit les prescriptions inappropriées d''antibiotiques de 22 % et amélioré les résultats cliniques des patients souffrant d''infections graves de 18 %. Le consortium prévoit de déployer l''outil dans 500 établissements de santé à travers 15 pays d''ici fin 2027.',
 'Artificial intelligence is emerging as a transformative tool in antimicrobial resistance surveillance across Africa. A consortium comprising the University of Cape Town, KEMRI in Kenya, the University of Ibadan in Nigeria, and the Institut Pasteur de Madagascar has developed and validated machine learning models capable of predicting antibiotic resistance profiles with an unprecedented accuracy of 89%.\n\nThe models, named AfriAMR-Predict, utilize deep neural networks trained on a database of over 2 million antibiograms collected from 200 African hospitals between 2018 and 2025. By integrating clinical variables (age, diagnosis, hospitalization history), geographic variables (region, urban/rural setting), and temporal variables (season, epidemiological trends), the models can recommend the most appropriate antibiotic treatment before culture results are even available.\n\nProfessor Tulio de Oliveira, bioinformatician at the University of Cape Town and lead architect of the project, explained that \"on a continent where fewer than 10% of antibiotic prescriptions are guided by an antibiogram, AI can substantially bridge this diagnostic gap.\" He added that the models are designed to run on smartphones with limited internet connectivity.\n\nA pilot study conducted in 20 Kenyan hospitals showed that using AfriAMR-Predict reduced inappropriate antibiotic prescriptions by 22% and improved clinical outcomes for patients with severe infections by 18%. The consortium plans to deploy the tool across 500 healthcare facilities in 15 countries by the end of 2027.',
 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&h=500&fit=crop',
 'published', 1, '2026-02-12 10:00:00', 756),

(4, 1,
 'rapid-diagnostic-tools-point-of-care-amr-detection',
 'Outils de diagnostic rapide pour la détection de la RAM au point de soins',
 'Rapid Diagnostic Tools for Point-of-Care AMR Detection',
 'Un dispositif de diagnostic rapide développé en Afrique du Sud permet d''identifier les bactéries résistantes en moins de 30 minutes. Cette innovation pourrait éliminer le recours aux antibiotiques à l''aveugle dans les cliniques rurales.',
 'A rapid diagnostic device developed in South Africa can identify resistant bacteria in under 30 minutes. This innovation could eliminate blind antibiotic prescribing in rural clinics across the continent.',
 'Le diagnostic rapide de la résistance aux antibiotiques au point de soins représente l''un des plus grands défis techniques de la lutte contre la RAM, particulièrement dans les contextes à ressources limitées. Une équipe de chercheurs de l''Université de Stellenbosch, en Afrique du Sud, vient de franchir une étape décisive avec le développement du dispositif RapidRESIST, capable d''identifier les bactéries résistantes aux antibiotiques en moins de 30 minutes à partir d''un simple échantillon clinique.\n\nLe dispositif, de la taille d''un smartphone, utilise une combinaison de microfluidique et de détection par impédance électrochimique pour détecter simultanément la présence bactérienne et les principaux mécanismes de résistance (production de BLSE, résistance aux carbapénèmes, résistance à la méticilline). Contrairement aux méthodes conventionnelles de culture qui nécessitent 48 à 72 heures, RapidRESIST fournit des résultats exploitables en temps réel, permettant aux cliniciens de prescrire un traitement ciblé dès la première consultation.\n\nLa professeure Bavesh Kana, directrice du programme de développement, a souligné que « RapidRESIST a été conçu dès le départ pour les réalités africaines : il fonctionne sans électricité stable, sans réfrigération des réactifs et avec une formation minimale de l''opérateur ». Le coût par test est estimé à 3 dollars, ce qui le rend accessible aux systèmes de santé à budget limité.\n\nUn essai clinique multicentrique impliquant 5 000 patients dans 50 cliniques rurales au Kenya, en Tanzanie et en Afrique du Sud est actuellement en cours. Les résultats préliminaires montrent une concordance de 92 % avec les méthodes de référence. Si ces résultats se confirment, RapidRESIST pourrait obtenir la préqualification de l''OMS d''ici la fin 2027 et être déployé à grande échelle à travers le continent.',
 'Rapid point-of-care diagnosis of antibiotic resistance represents one of the greatest technical challenges in the fight against AMR, particularly in resource-limited settings. A team of researchers from Stellenbosch University in South Africa has just achieved a decisive breakthrough with the development of the RapidRESIST device, capable of identifying antibiotic-resistant bacteria in under 30 minutes from a simple clinical sample.\n\nThe device, roughly the size of a smartphone, uses a combination of microfluidics and electrochemical impedance detection to simultaneously detect bacterial presence and key resistance mechanisms (ESBL production, carbapenem resistance, methicillin resistance). Unlike conventional culture methods that require 48 to 72 hours, RapidRESIST provides actionable results in real time, enabling clinicians to prescribe targeted treatment from the first consultation.\n\nProfessor Bavesh Kana, program development director, emphasized that \"RapidRESIST was designed from the ground up for African realities: it operates without stable electricity, without reagent refrigeration, and with minimal operator training.\" The cost per test is estimated at $3, making it accessible to budget-constrained health systems.\n\nA multicenter clinical trial involving 5,000 patients across 50 rural clinics in Kenya, Tanzania, and South Africa is currently underway. Preliminary results show 92% concordance with reference methods. If these results are confirmed, RapidRESIST could obtain WHO prequalification by the end of 2027 and be deployed at scale across the continent.',
 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=800&h=500&fit=crop',
 'published', 0, '2026-03-05 07:30:00', 623),

(4, 1,
 'genomic-sequencing-networks-amr-africa',
 'Réseaux de séquençage génomique pour la RAM en Afrique : de la recherche à la surveillance',
 'Genomic Sequencing Networks for AMR in Africa: From Research to Routine Surveillance',
 'Le réseau Africa PGI (Pathogen Genomics Initiative) a installé 100 séquenceurs dans 35 pays africains. Le séquençage génomique des pathogènes résistants devient un outil de surveillance de routine.',
 'The Africa PGI (Pathogen Genomics Initiative) network has installed 100 sequencers across 35 African countries. Genomic sequencing of resistant pathogens is becoming a routine surveillance tool.',
 'Le séquençage génomique des pathogènes résistants aux antibiotiques est en train de passer du stade de la recherche académique à celui de la surveillance de routine en Afrique, grâce au réseau Africa Pathogen Genomics Initiative (Africa PGI). Lancé en 2022 avec un financement initial de 100 millions de dollars du CDC américain et du Wellcome Trust, le réseau a franchi une étape symbolique en installant son centième séquenceur dans un laboratoire de santé publique africain.\n\nLes 100 séquenceurs — principalement des plateformes Oxford Nanopore MinION et Illumina MiSeq — sont désormais opérationnels dans 35 pays africains. Plus de 1 500 scientifiques africains ont été formés aux techniques de séquençage et à l''analyse bioinformatique. En 2025, le réseau a produit plus de 50 000 séquences génomiques de pathogènes résistants, contribuant significativement à la compréhension de l''épidémiologie moléculaire de la RAM sur le continent.\n\nLe Dr Christian Happi, directeur du Centre africain d''excellence en génomique des maladies infectieuses (ACEGID) au Nigeria, a déclaré que « le séquençage génomique n''est plus un luxe réservé aux laboratoires de recherche des pays riches. C''est un outil de santé publique essentiel que l''Afrique est désormais en mesure de déployer à grande échelle ». Il a cité l''exemple du Nigeria, qui utilise désormais le séquençage de routine pour orienter les politiques de traitement empirique dans ses hôpitaux de référence.\n\nLe réseau Africa PGI a également développé une infrastructure cloud de données génomiques, hébergée sur le continent, qui permet le partage sécurisé des séquences entre pays tout en respectant les principes de souveraineté des données. Cette plateforme alimente un système d''alerte précoce capable de détecter l''émergence de nouveaux mécanismes de résistance en temps quasi réel.',
 'Genomic sequencing of antibiotic-resistant pathogens is transitioning from academic research to routine surveillance in Africa, thanks to the Africa Pathogen Genomics Initiative (Africa PGI) network. Launched in 2022 with initial funding of $100 million from the US CDC and the Wellcome Trust, the network has reached a symbolic milestone by installing its hundredth sequencer in an African public health laboratory.\n\nThe 100 sequencers — primarily Oxford Nanopore MinION and Illumina MiSeq platforms — are now operational across 35 African countries. Over 1,500 African scientists have been trained in sequencing techniques and bioinformatics analysis. In 2025, the network produced more than 50,000 genomic sequences of resistant pathogens, contributing significantly to understanding the molecular epidemiology of AMR on the continent.\n\nDr. Christian Happi, director of the African Centre of Excellence for Genomics of Infectious Diseases (ACEGID) in Nigeria, stated that \"genomic sequencing is no longer a luxury reserved for research laboratories in wealthy countries. It is an essential public health tool that Africa is now capable of deploying at scale.\" He cited Nigeria''s example, which now uses routine sequencing to guide empirical treatment policies in its referral hospitals.\n\nThe Africa PGI network has also developed a cloud-based genomic data infrastructure, hosted on the continent, enabling secure sequence sharing between countries while respecting data sovereignty principles. This platform feeds an early warning system capable of detecting the emergence of new resistance mechanisms in near-real time.',
 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=500&fit=crop',
 'published', 0, '2026-04-25 13:45:00', 412),

(4, 1,
 'digital-health-platforms-amr-data-integration',
 'Plateformes de santé numérique pour l''intégration des données RAM en Afrique',
 'Digital Health Platforms for AMR Data Integration Across Africa',
 'La plateforme DHIS2-AMR, déployée dans 25 pays africains, permet pour la première fois l''intégration des données de résistance aux antibiotiques dans les systèmes nationaux d''information sanitaire. Un pas décisif vers la prise de décision basée sur les données.',
 'The DHIS2-AMR platform, deployed across 25 African countries, enables the integration of antibiotic resistance data into national health information systems for the first time. A decisive step toward data-driven decision making.',
 'L''intégration des données de résistance aux antimicrobiens dans les systèmes d''information sanitaire nationaux représente un défi majeur pour les pays africains. La plupart des données de RAM restent cloisonnées dans des registres hospitaliers papier ou des bases de données de recherche inaccessibles aux décideurs politiques. La plateforme DHIS2-AMR, développée en collaboration avec l''Université d''Oslo et le CDC Afrique, vise à résoudre ce problème en intégrant un module dédié à la RAM dans le système DHIS2, déjà utilisé par plus de 40 pays africains pour leur surveillance sanitaire de routine.\n\nLe module DHIS2-AMR permet aux laboratoires de microbiologie de saisir directement les résultats d''antibiogrammes dans le système national, générant automatiquement des rapports de surveillance standardisés conformes au cadre GLASS (Global Antimicrobial Resistance and Use Surveillance System) de l''OMS. Les tableaux de bord interactifs offrent aux responsables de santé publique une vue d''ensemble en temps réel des tendances de résistance dans leur pays.\n\nLe Dr Bob Jolliffe, architecte principal de DHIS2, a souligné que « l''un des plus grands obstacles à la lutte contre la RAM en Afrique n''est pas le manque de données, mais l''incapacité à les transformer en informations exploitables pour la prise de décision. DHIS2-AMR résout ce problème en plaçant les données de RAM au cœur du système d''information sanitaire national ».\n\nDepuis son lancement pilote en 2024, le module a été déployé dans 25 pays et intègre désormais les données de plus de 300 laboratoires. Les premiers pays à l''avoir adopté — le Kenya, la Tanzanie et l''Éthiopie — rapportent une amélioration significative de la qualité et de la complétude de leurs rapports GLASS annuels. Le CDC Afrique vise un déploiement dans les 55 pays membres de l''UA d''ici 2029.',
 'Integrating antimicrobial resistance data into national health information systems represents a major challenge for African countries. Most AMR data remain siloed in paper-based hospital registers or research databases inaccessible to policymakers. The DHIS2-AMR platform, developed in collaboration with the University of Oslo and Africa CDC, aims to solve this problem by integrating a dedicated AMR module into the DHIS2 system, already used by over 40 African countries for routine health surveillance.\n\nThe DHIS2-AMR module allows microbiology laboratories to enter antibiogram results directly into the national system, automatically generating standardized surveillance reports compliant with WHO''s GLASS (Global Antimicrobial Resistance and Use Surveillance System) framework. Interactive dashboards provide public health officials with a real-time overview of resistance trends in their country.\n\nDr. Bob Jolliffe, lead architect of DHIS2, emphasized that \"one of the greatest obstacles to combating AMR in Africa is not the lack of data, but the inability to transform it into actionable information for decision-making. DHIS2-AMR solves this problem by placing AMR data at the heart of the national health information system.\"\n\nSince its pilot launch in 2024, the module has been deployed in 25 countries and now integrates data from over 300 laboratories. The first countries to adopt it — Kenya, Tanzania, and Ethiopia — report significant improvement in the quality and completeness of their annual GLASS reports. Africa CDC aims for deployment across all 55 AU member states by 2029.',
 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=500&fit=crop',
 'published', 0, '2026-05-30 09:15:00', 198),

(4, 1,
 'novel-antimicrobials-african-biodiversity-drug-discovery',
 'Nouveaux antimicrobiens issus de la biodiversité africaine : la renaissance de la découverte de médicaments',
 'Novel Antimicrobials From African Biodiversity: A Drug Discovery Renaissance',
 'Des chercheurs africains exploitent la biodiversité unique du continent pour découvrir de nouveaux composés antimicrobiens. Trois molécules prometteuses issues de micro-organismes du sol africain entrent en essais précliniques.',
 'African researchers are harnessing the continent''s unique biodiversity to discover novel antimicrobial compounds. Three promising molecules derived from African soil microorganisms are entering preclinical trials.',
 'La crise mondiale de la résistance aux antimicrobiens est aggravée par l''assèchement du pipeline de découverte de nouveaux antibiotiques. Cependant, un mouvement émergent de chercheurs africains est en train de renverser cette tendance en exploitant la biodiversité exceptionnelle et largement inexplorée du continent pour identifier de nouveaux composés antimicrobiens. Le projet AfricaBioAntibiotic, coordonné par l''Université de Pretoria et l''Institut H3D de l''Université du Cap, est à la pointe de cette renaissance.\n\nLe projet a constitué une biothèque de plus de 50 000 micro-organismes isolés à partir d''échantillons de sol, de plantes médicinales et d''environnements extrêmes collectés dans 20 pays africains. Les criblages à haut débit ont identifié 127 extraits présentant une activité antimicrobienne significative, dont trois molécules particulièrement prometteuses qui ciblent des mécanismes d''action inédits contre les bactéries Gram-négatives multirésistantes.\n\nLe professeur Kelly Chibale, directeur de l''Institut H3D et pionnier de la découverte de médicaments en Afrique, a déclaré que « la biodiversité africaine recèle un trésor de molécules antimicrobiennes que le monde n''a pas encore exploré. Notre objectif est de transformer cette richesse naturelle en solutions thérapeutiques, tout en garantissant que les bénéfices reviennent aux communautés et aux pays d''origine ». Il a souligné l''importance du protocole de Nagoya pour assurer un partage équitable des avantages.\n\nLes trois molécules candidates — baptisées AfriMycin-1, AfriMycin-2 et AfriMycin-3 — ont montré une activité puissante contre Klebsiella pneumoniae résistante aux carbapénèmes et Acinetobacter baumannii panrésistant in vitro. Les essais précliniques, financés par le GARDP et le Wellcome Trust à hauteur de 15 millions de dollars, débuteront au troisième trimestre 2026 dans des installations certifiées BPL à Cape Town et Nairobi.',
 'The global antimicrobial resistance crisis is compounded by a drying pipeline for new antibiotic discovery. However, an emerging movement of African researchers is reversing this trend by harnessing the continent''s exceptional and largely unexplored biodiversity to identify novel antimicrobial compounds. The AfricaBioAntibiotic project, coordinated by the University of Pretoria and the H3D Institute at the University of Cape Town, is at the forefront of this renaissance.\n\nThe project has assembled a biobank of over 50,000 microorganisms isolated from soil samples, medicinal plants, and extreme environments collected across 20 African countries. High-throughput screening has identified 127 extracts with significant antimicrobial activity, including three particularly promising molecules that target novel mechanisms of action against multidrug-resistant Gram-negative bacteria.\n\nProfessor Kelly Chibale, director of the H3D Institute and a pioneer in African drug discovery, stated that \"African biodiversity holds a treasure trove of antimicrobial molecules that the world has yet to explore. Our goal is to transform this natural wealth into therapeutic solutions while ensuring that benefits flow back to the communities and countries of origin.\" He emphasized the importance of the Nagoya Protocol for ensuring equitable benefit sharing.\n\nThe three candidate molecules — named AfriMycin-1, AfriMycin-2, and AfriMycin-3 — have shown potent activity against carbapenem-resistant Klebsiella pneumoniae and pandrug-resistant Acinetobacter baumannii in vitro. Preclinical trials, funded by GARDP and the Wellcome Trust at $15 million, will begin in the third quarter of 2026 at GLP-certified facilities in Cape Town and Nairobi.',
 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&h=500&fit=crop',
 'published', 0, '2026-06-25 16:00:00', 145);
